const express = require('express');
const router = express.Router();
const Anthropic = require('@anthropic-ai/sdk');
const { logger } = require('../utils/logger');

// ── POST /api/report/dmca ─────────────────────────────────────────────────────
router.post('/dmca', async (req, res) => {
  const { platform, user, caption, contentType, analysisData, reporter } = req.body;
  if (!platform) return res.status(400).json({ error: 'platform required' });

  const caseId = 'VM-' + Date.now().toString(36).toUpperCase();
  const simPct = Math.round((analysisData?.fingerprint_match || analysisData?.match_score || 0.8) * 100);
  const intPct = Math.round((analysisData?.integrity_score || 0.3) * 100);
  const mlPct = Math.round((analysisData?.ml_manipulation_probability || 0.8) * 100);
  const decision = analysisData?.decision || 'TAKEDOWN';
  const reportedBy = reporter ? (reporter.startsWith('@') ? reporter : '@' + reporter) : 'Verified User';
  const postUrl = `https://${platform.toLowerCase().replace(/\s/g, '').replace('/x', '')}.com/post/${caseId.slice(-8)}`;

  const report = `VeriMedia AI — DMCA Takedown Report
Case ID: ${caseId}
Generated: ${new Date().toUTCString()}
Reported by: ${reportedBy}
${'='.repeat(50)}

TO: ${platform} Trust & Safety Team

SUBJECT: Copyright Infringement Notice – Unauthorized Use of Protected Media – Case ${caseId}

Pursuant to the Digital Millennium Copyright Act, 17 U.S.C. § 512(c), VeriMedia AI Rights Management hereby requests immediate removal of the following infringing content.

INFRINGING CONTENT
------------------
Platform: ${platform}
Account: ${user || 'Unknown'}
Caption: "${(caption || '').slice(0, 120)}"
URL: ${postUrl}
Content Type: ${contentType || 'general'}
Detection Timestamp: ${new Date().toUTCString()}

EVIDENCE SUMMARY
----------------
Decision: ${decision}
Visual Similarity: ${simPct}% match to registered asset
ML Classifier: ${analysisData?.ml_label || 'TAMPERED'} — ${mlPct}% manipulation probability
Integrity Score: ${intPct}% — ${intPct < 40 ? 'heavily manipulated' : intPct < 70 ? 'moderately degraded' : 'intact'}
Manipulation Type: ${analysisData?.scenario || 'unauthorized modification'}
Watermark: AES-256 encrypted watermark verified in original (absent from infringing post)
Evidence Files: frame_comparison_${caseId}.png · heatmap_overlay_${caseId}.png

I declare under penalty of perjury that this information is accurate and that I am authorized to act on behalf of the exclusive rights holder.

${reportedBy}
VeriMedia AI Rights Management
${'─'.repeat(50)}
⚠ This report was generated by VeriMedia AI. Review before submitting to platform legal team.`;

  logger.info('DMCA report generated', { caseId, platform });

  res.json({
    success: true,
    caseId,
    report,
    metadata: { platform, user, decision, simPct, intPct, reportedBy, generatedAt: new Date().toISOString() },
  });
});

// ── POST /api/report/analysis ─────────────────────────────────────────────────
router.post('/analysis', async (req, res) => {
  const { platform, user, similarity, integrity, decision, severity, contentType, reasoning } = req.body;

  const caseRef = 'VM-' + Date.now().toString(36).toUpperCase();
  const trustScore = ((similarity || 0) * (integrity || 0) * 100).toFixed(0);

  const report = `VeriMedia AI — Full Analysis Export
Generated: ${new Date().toUTCString()}
Case Reference: ${caseRef}
${'='.repeat(55)}

DETECTION SUMMARY
-----------------
Platform: ${platform || 'Unknown'}
Account: ${user || 'Unknown'}
Content Type: ${contentType || 'Unknown'}
Decision: ${decision || 'Unknown'}
Severity: ${severity || 'Unknown'}

SCORE BREAKDOWN
---------------
Visual Similarity: ${Math.round((similarity || 0) * 100)}%
Integrity Score: ${Math.round((integrity || 0) * 100)}%
Trust Score (match × integrity): ${trustScore}%

AI REASONING
------------
${(reasoning || ['No reasoning data available.']).map((r, i) => `${i + 1}. ${r}`).join('\n')}

RECOMMENDED ACTION
------------------
${decision === 'TAKEDOWN' || decision === 'EMERGENCY_TAKEDOWN'
  ? 'File DMCA takedown notice immediately. Preserve evidence package.'
  : decision === 'REVIEW'
    ? 'Manual review required. Insufficient confidence for automated enforcement.'
    : 'No enforcement action required. Content appears authorized.'}

SYSTEM NOTES
------------
Trust formula: match_score × integrity_score
Thresholds: >0.75 ALLOW · 0.40–0.75 REVIEW · <0.40 TAKEDOWN · <0.30 + viral>85 EMERGENCY_TAKEDOWN

---
VeriMedia AI — AI Content Intelligence Pipeline
Detection · Verification · Enforcement`;

  res.json({ success: true, caseRef, report, generatedAt: new Date().toISOString() });
});

// ── POST /api/report/ai-dmca ──────────────────────────────────────────────────
// AI-enhanced DMCA using Claude for legal language
router.post('/ai-dmca', async (req, res) => {
  const { platform, user, analysisData, reporter } = req.body;
  const apiKey = req.headers['x-api-key'] || process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return res.status(401).json({ error: 'API key required' });
  if (!platform) return res.status(400).json({ error: 'platform required' });

  try {
    const client = new Anthropic({ apiKey });
    const sim = Math.round((analysisData?.match_score || 0.8) * 100);
    const prompt = `Draft a professional DMCA takedown notice for the following copyright infringement:
Platform: ${platform}
Infringing account: ${user || 'Unknown'}
AI Detection result: ${analysisData?.decision || 'TAKEDOWN'}
Visual similarity: ${sim}%
Manipulation type: ${analysisData?.scenario || 'unauthorized repost'}

Write a formal, legally-grounded notice in 150 words. Be precise and professional. Do not add disclaimers.`;

    const r = await client.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 400,
      messages: [{ role: 'user', content: prompt }],
    });
    const aiNotice = r.content.map(b => b.type === 'text' ? b.text : '').join('').trim();
    const caseId = 'VM-' + Date.now().toString(36).toUpperCase();
    res.json({ success: true, caseId, aiNotice, generatedAt: new Date().toISOString() });
  } catch (err) {
    logger.error('AI DMCA failed', { message: err.message });
    res.status(500).json({ error: 'AI DMCA generation failed' });
  }
});

module.exports = router;
